# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rx_Memo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rx_Memo
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCoreData'

  target 'Rx_MemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rx_MemoUITests' do
    # Pods for testing
  end

end
